#!/bin/bash
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 1 --device cuda:0 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 2 --device cuda:1 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 3 --device cuda:2 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 4 --device cuda:3 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 5 --device cuda:4 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 6 --device cuda:5 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 7 --device cuda:6 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 8 --device cuda:7 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 9 --device cuda:0 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 10 --device cuda:1 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 11 --device cuda:2 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 12 --device cuda:3 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 13 --device cuda:4 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 14 --device cuda:5 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 15 --device cuda:6 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 16 --device cuda:7 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 17 --device cuda:0 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 18 --device cuda:1 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 19 --device cuda:2 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_AdaODQN.json --config_idx 20 --device cuda:3 > MERL_Asterix_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 1 --device cuda:4 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 3 --device cuda:5 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 5 --device cuda:6 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 7 --device cuda:7 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 9 --device cuda:0 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 11 --device cuda:1 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 13 --device cuda:2 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 15 --device cuda:3 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 17 --device cuda:4 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 19 --device cuda:5 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 21 --device cuda:6 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 23 --device cuda:7 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 25 --device cuda:0 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 27 --device cuda:1 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 29 --device cuda:2 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 31 --device cuda:3 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 33 --device cuda:4 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 35 --device cuda:5 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 37 --device cuda:6 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 39 --device cuda:7 > MERL_Asterix_dqn.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 2 --device cuda:0 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 4 --device cuda:1 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 6 --device cuda:2 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 8 --device cuda:3 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 10 --device cuda:4 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 12 --device cuda:5 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 14 --device cuda:6 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 16 --device cuda:7 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 18 --device cuda:0 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 20 --device cuda:1 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 22 --device cuda:2 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 24 --device cuda:3 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 26 --device cuda:4 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 28 --device cuda:5 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 30 --device cuda:6 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 32 --device cuda:7 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 34 --device cuda:0 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 36 --device cuda:1 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 38 --device cuda:2 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_dqn.json --config_idx 40 --device cuda:3 > MERL_Asterix_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 1 --device cuda:4 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 2 --device cuda:5 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 3 --device cuda:6 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 4 --device cuda:7 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 5 --device cuda:0 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 6 --device cuda:1 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 7 --device cuda:2 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 8 --device cuda:3 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 9 --device cuda:4 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 10 --device cuda:5 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 11 --device cuda:6 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 12 --device cuda:7 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 13 --device cuda:0 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 14 --device cuda:1 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 15 --device cuda:2 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 16 --device cuda:3 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 17 --device cuda:4 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 18 --device cuda:5 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 19 --device cuda:6 > MERL_Asterix_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Weighted.json --config_idx 20 --device cuda:7 > MERL_Asterix_Weighted.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 1 --device cuda:0 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 2 --device cuda:1 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 3 --device cuda:2 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 4 --device cuda:3 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 5 --device cuda:4 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 6 --device cuda:5 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 7 --device cuda:6 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 8 --device cuda:7 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 9 --device cuda:0 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 10 --device cuda:1 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 11 --device cuda:2 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 12 --device cuda:3 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 13 --device cuda:4 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 14 --device cuda:5 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 15 --device cuda:6 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 16 --device cuda:7 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 17 --device cuda:0 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 18 --device cuda:1 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 19 --device cuda:2 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Maxmin.json --config_idx 20 --device cuda:3 > MERL_Asterix_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 1 --device cuda:4 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 2 --device cuda:5 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 3 --device cuda:6 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 4 --device cuda:7 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 5 --device cuda:0 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 6 --device cuda:1 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 7 --device cuda:2 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 8 --device cuda:3 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 9 --device cuda:4 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 10 --device cuda:5 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 11 --device cuda:6 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 12 --device cuda:7 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 13 --device cuda:0 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 14 --device cuda:1 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 15 --device cuda:2 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 16 --device cuda:3 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 17 --device cuda:4 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 18 --device cuda:5 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 19 --device cuda:6 > MERL_Asterix_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_Averaged.json --config_idx 20 --device cuda:7 > MERL_Asterix_Averaged.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 1 --device cuda:0 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 2 --device cuda:1 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 3 --device cuda:2 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 4 --device cuda:3 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 5 --device cuda:4 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 6 --device cuda:5 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 7 --device cuda:6 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 8 --device cuda:7 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 9 --device cuda:0 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 10 --device cuda:1 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 11 --device cuda:2 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 12 --device cuda:3 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 13 --device cuda:4 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 14 --device cuda:5 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 15 --device cuda:6 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 16 --device cuda:7 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 17 --device cuda:0 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 18 --device cuda:1 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 19 --device cuda:2 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_EBDQN.json --config_idx 20 --device cuda:3 > MERL_Asterix_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 1 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 5 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 9 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 13 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 17 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 21 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 25 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 29 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 33 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 37 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 41 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 45 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 49 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 53 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 57 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 61 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 65 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 69 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 73 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 77 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 2 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 6 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 10 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 14 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 18 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 22 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 26 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 30 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 34 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 38 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 42 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 46 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 50 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 54 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 58 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 62 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 66 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 70 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 74 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 78 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 3 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 7 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 11 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 15 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 19 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 23 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 27 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 31 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 35 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 39 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 43 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 47 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 51 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 55 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 59 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 63 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 67 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 71 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 75 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 79 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 4 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 8 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 12 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 16 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 20 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 24 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 28 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 32 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 36 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 40 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 44 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 48 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 52 --device cuda:4 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 56 --device cuda:5 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 60 --device cuda:6 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 64 --device cuda:7 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 68 --device cuda:0 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 72 --device cuda:1 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 76 --device cuda:2 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_Asterix_ErrorClipDQN.json --config_idx 80 --device cuda:3 > MERL_Asterix_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 1 --device cuda:4 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 2 --device cuda:5 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 3 --device cuda:6 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 4 --device cuda:7 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 5 --device cuda:0 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 6 --device cuda:1 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 7 --device cuda:2 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 8 --device cuda:3 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 9 --device cuda:4 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 10 --device cuda:5 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 11 --device cuda:6 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 12 --device cuda:7 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 13 --device cuda:0 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 14 --device cuda:1 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 15 --device cuda:2 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 16 --device cuda:3 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 17 --device cuda:4 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 18 --device cuda:5 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 19 --device cuda:6 > MERL_breakout_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_AdaODQN.json --config_idx 20 --device cuda:7 > MERL_breakout_AdaODQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 1 --device cuda:0 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 3 --device cuda:1 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 5 --device cuda:2 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 7 --device cuda:3 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 9 --device cuda:4 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 11 --device cuda:5 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 13 --device cuda:6 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 15 --device cuda:7 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 17 --device cuda:0 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 19 --device cuda:1 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 21 --device cuda:2 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 23 --device cuda:3 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 25 --device cuda:4 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 27 --device cuda:5 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 29 --device cuda:6 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 31 --device cuda:7 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 33 --device cuda:0 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 35 --device cuda:1 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 37 --device cuda:2 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 39 --device cuda:3 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 2 --device cuda:4 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 4 --device cuda:5 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 6 --device cuda:6 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 8 --device cuda:7 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 10 --device cuda:0 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 12 --device cuda:1 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 14 --device cuda:2 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 16 --device cuda:3 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 18 --device cuda:4 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 20 --device cuda:5 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 22 --device cuda:6 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 24 --device cuda:7 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 26 --device cuda:0 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 28 --device cuda:1 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 30 --device cuda:2 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 32 --device cuda:3 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 34 --device cuda:4 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 36 --device cuda:5 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 38 --device cuda:6 > MERL_breakout_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_dqn.json --config_idx 40 --device cuda:7 > MERL_breakout_dqn.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 1 --device cuda:0 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 2 --device cuda:1 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 3 --device cuda:2 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 4 --device cuda:3 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 5 --device cuda:4 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 6 --device cuda:5 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 7 --device cuda:6 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 8 --device cuda:7 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 9 --device cuda:0 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 10 --device cuda:1 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 11 --device cuda:2 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 12 --device cuda:3 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 13 --device cuda:4 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 14 --device cuda:5 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 15 --device cuda:6 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 16 --device cuda:7 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 17 --device cuda:0 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 18 --device cuda:1 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 19 --device cuda:2 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Weighted.json --config_idx 20 --device cuda:3 > MERL_breakout_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 1 --device cuda:4 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 2 --device cuda:5 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 3 --device cuda:6 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 4 --device cuda:7 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 5 --device cuda:0 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 6 --device cuda:1 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 7 --device cuda:2 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 8 --device cuda:3 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 9 --device cuda:4 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 10 --device cuda:5 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 11 --device cuda:6 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 12 --device cuda:7 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 13 --device cuda:0 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 14 --device cuda:1 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 15 --device cuda:2 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 16 --device cuda:3 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 17 --device cuda:4 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 18 --device cuda:5 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 19 --device cuda:6 > MERL_breakout_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Maxmin.json --config_idx 20 --device cuda:7 > MERL_breakout_Maxmin.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 1 --device cuda:0 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 2 --device cuda:1 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 3 --device cuda:2 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 4 --device cuda:3 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 5 --device cuda:4 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 6 --device cuda:5 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 7 --device cuda:6 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 8 --device cuda:7 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 9 --device cuda:0 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 10 --device cuda:1 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 11 --device cuda:2 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 12 --device cuda:3 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 13 --device cuda:4 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 14 --device cuda:5 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 15 --device cuda:6 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 16 --device cuda:7 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 17 --device cuda:0 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 18 --device cuda:1 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 19 --device cuda:2 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_Averaged.json --config_idx 20 --device cuda:3 > MERL_breakout_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 1 --device cuda:4 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 2 --device cuda:5 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 3 --device cuda:6 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 4 --device cuda:7 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 5 --device cuda:0 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 6 --device cuda:1 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 7 --device cuda:2 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 8 --device cuda:3 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 9 --device cuda:4 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 10 --device cuda:5 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 11 --device cuda:6 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 12 --device cuda:7 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 13 --device cuda:0 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 14 --device cuda:1 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 15 --device cuda:2 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 16 --device cuda:3 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 17 --device cuda:4 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 18 --device cuda:5 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 19 --device cuda:6 > MERL_breakout_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_EBDQN.json --config_idx 20 --device cuda:7 > MERL_breakout_EBDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 1 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 5 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 9 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 13 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 17 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 21 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 25 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 29 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 33 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 37 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 41 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 45 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 49 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 53 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 57 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 61 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 65 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 69 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 73 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 77 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 2 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 6 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 10 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 14 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 18 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 22 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 26 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 30 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 34 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 38 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 42 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 46 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 50 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 54 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 58 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 62 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 66 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 70 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 74 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 78 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 3 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 7 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 11 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 15 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 19 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 23 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 27 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 31 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 35 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 39 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 43 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 47 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 51 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 55 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 59 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 63 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 67 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 71 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 75 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 79 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 4 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 8 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 12 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 16 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 20 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 24 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 28 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 32 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 36 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 40 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 44 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 48 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 52 --device cuda:0 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 56 --device cuda:1 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 60 --device cuda:2 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 64 --device cuda:3 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 68 --device cuda:4 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 72 --device cuda:5 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 76 --device cuda:6 > MERL_breakout_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_breakout_ErrorClipDQN.json --config_idx 80 --device cuda:7 > MERL_breakout_ErrorClipDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 1 --device cuda:0 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 2 --device cuda:1 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 3 --device cuda:2 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 4 --device cuda:3 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 5 --device cuda:4 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 6 --device cuda:5 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 7 --device cuda:6 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 8 --device cuda:7 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 9 --device cuda:0 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 10 --device cuda:1 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 11 --device cuda:2 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 12 --device cuda:3 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 13 --device cuda:4 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 14 --device cuda:5 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 15 --device cuda:6 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 16 --device cuda:7 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 17 --device cuda:0 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 18 --device cuda:1 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 19 --device cuda:2 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_AdaODQN.json --config_idx 20 --device cuda:3 > MERL_seaquestv1_AdaODQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 1 --device cuda:4 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 3 --device cuda:5 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 5 --device cuda:6 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 7 --device cuda:7 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 9 --device cuda:0 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 11 --device cuda:1 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 13 --device cuda:2 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 15 --device cuda:3 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 17 --device cuda:4 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 19 --device cuda:5 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 21 --device cuda:6 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 23 --device cuda:7 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 25 --device cuda:0 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 27 --device cuda:1 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 29 --device cuda:2 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 31 --device cuda:3 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 33 --device cuda:4 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 35 --device cuda:5 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 37 --device cuda:6 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 39 --device cuda:7 > MERL_seaquestv1_dqn.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 2 --device cuda:0 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 4 --device cuda:1 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 6 --device cuda:2 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 8 --device cuda:3 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 10 --device cuda:4 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 12 --device cuda:5 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 14 --device cuda:6 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 16 --device cuda:7 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 18 --device cuda:0 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 20 --device cuda:1 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 22 --device cuda:2 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 24 --device cuda:3 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 26 --device cuda:4 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 28 --device cuda:5 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 30 --device cuda:6 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 32 --device cuda:7 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 34 --device cuda:0 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 36 --device cuda:1 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 38 --device cuda:2 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_dqn.json --config_idx 40 --device cuda:3 > MERL_seaquestv1_dqn.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 1 --device cuda:4 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 2 --device cuda:5 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 3 --device cuda:6 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 4 --device cuda:7 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 5 --device cuda:0 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 6 --device cuda:1 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 7 --device cuda:2 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 8 --device cuda:3 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 9 --device cuda:4 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 10 --device cuda:5 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 11 --device cuda:6 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 12 --device cuda:7 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 13 --device cuda:0 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 14 --device cuda:1 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 15 --device cuda:2 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 16 --device cuda:3 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 17 --device cuda:4 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 18 --device cuda:5 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 19 --device cuda:6 > MERL_seaquestv1_Weighted.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Weighted.json --config_idx 20 --device cuda:7 > MERL_seaquestv1_Weighted.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 1 --device cuda:0 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 2 --device cuda:1 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 3 --device cuda:2 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 4 --device cuda:3 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 5 --device cuda:4 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 6 --device cuda:5 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 7 --device cuda:6 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 8 --device cuda:7 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 9 --device cuda:0 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 10 --device cuda:1 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 11 --device cuda:2 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 12 --device cuda:3 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 13 --device cuda:4 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 14 --device cuda:5 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 15 --device cuda:6 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 16 --device cuda:7 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 17 --device cuda:0 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 18 --device cuda:1 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 19 --device cuda:2 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Maxmin.json --config_idx 20 --device cuda:3 > MERL_seaquestv1_Maxmin.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 1 --device cuda:4 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 2 --device cuda:5 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 3 --device cuda:6 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 4 --device cuda:7 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 5 --device cuda:0 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 6 --device cuda:1 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 7 --device cuda:2 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 8 --device cuda:3 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 9 --device cuda:4 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 10 --device cuda:5 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 11 --device cuda:6 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 12 --device cuda:7 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 13 --device cuda:0 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 14 --device cuda:1 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 15 --device cuda:2 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 16 --device cuda:3 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 17 --device cuda:4 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 18 --device cuda:5 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 19 --device cuda:6 > MERL_seaquestv1_Averaged.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_Averaged.json --config_idx 20 --device cuda:7 > MERL_seaquestv1_Averaged.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 1 --device cuda:0 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 2 --device cuda:1 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 3 --device cuda:2 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 4 --device cuda:3 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 5 --device cuda:4 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 6 --device cuda:5 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 7 --device cuda:6 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 8 --device cuda:7 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 9 --device cuda:0 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 10 --device cuda:1 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 11 --device cuda:2 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 12 --device cuda:3 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 13 --device cuda:4 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 14 --device cuda:5 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 15 --device cuda:6 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 16 --device cuda:7 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 17 --device cuda:0 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 18 --device cuda:1 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 19 --device cuda:2 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_EBDQN.json --config_idx 20 --device cuda:3 > MERL_seaquestv1_EBDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 1 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 5 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 9 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 13 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 17 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 21 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 25 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 29 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 33 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 37 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 41 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 45 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 49 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 53 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 57 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 61 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 65 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 69 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 73 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 77 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 2 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 6 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 10 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 14 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 18 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 22 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 26 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 30 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 34 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 38 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 42 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 46 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 50 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 54 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 58 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 62 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 66 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 70 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 74 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 78 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 3 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 7 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 11 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 15 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 19 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 23 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 27 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 31 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 35 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 39 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 43 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 47 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 51 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 55 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 59 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 63 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 67 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 71 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 75 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 79 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
wait
sleep 30
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 4 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 8 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 12 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 16 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 20 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 24 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 28 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 32 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 36 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 40 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 44 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 48 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 52 --device cuda:4 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 56 --device cuda:5 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 60 --device cuda:6 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 64 --device cuda:7 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 68 --device cuda:0 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 72 --device cuda:1 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 76 --device cuda:2 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
nohup python main.py --config_file ./configs/MERL_seaquestv1_ErrorClipDQN.json --config_idx 80 --device cuda:3 > MERL_seaquestv1_ErrorClipDQN.out 2>&1 &
wait
sleep 30
